# Generated by Django 4.0.4 on 2022-04-22 23:19

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='endereco',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
