# Generated by Django 4.0.4 on 2022-05-03 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_foto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foto_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uf',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(default='', max_length=15, null=True)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9, null=True)),
                ('endereco', models.CharField(default='', max_length=150, null=True)),
                ('uf', localflavor.br.models.BRStateField(default='', max_length=2, null=True)),
                ('cidade', models.CharField(default='', max_length=50, null=True)),
                ('foto_user', models.ImageField(blank=True, default='', upload_to='fotos/%d/%m/%Y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
