# Generated by Django 4.0.4 on 2022-05-03 03:09

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_cep_remove_user_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='foto_user',
            field=models.ImageField(blank=True, default='', upload_to='fotos/%d/%m/%Y'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uf',
            field=localflavor.br.models.BRStateField(default='', max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
