# Generated by Django 4.0.4 on 2022-05-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_post_conteudo_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
