# Generated by Django 4.0.4 on 2022-04-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
                ('nome', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField(default=0)),
                ('descricao', models.TextField(max_length=500)),
                ('disponivel', models.BooleanField(default=False)),
                ('fornecedor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criacao'],
            },
        ),
    ]
