# Generated by Django 4.0.4 on 2022-04-21 17:36

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('endereco', models.CharField(default='', max_length=150)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
            ],
        ),
    ]
