# Generated by Django 4.0.4 on 2022-04-21 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em: '),
        ),
        migrations.AddField(
            model_name='cliente',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em: '),
            preserve_default=False,
        ),
    ]
