# Generated by Django 4.0.4 on 2022-04-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_atualizacao_cliente_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-criacao'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
